# Generated by Django 3.2.4 on 2021-06-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210623_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='Blog',
        ),
    ]
