# Generated by Django 3.2.4 on 2021-06-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
        migrations.AlterField(
            model_name='blog',
            name='authorName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userName',
            field=models.CharField(max_length=100),
        ),
    ]
