# Generated by Django 3.2.4 on 2021-06-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_blogmodel_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categoryId',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
