# Generated by Django 3.2.4 on 2021-06-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categoryId',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blogId',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
        migrations.AddField(
            model_name='image',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
        migrations.AddField(
            model_name='image',
            name='imageData',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='image',
            name='imageType',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
