# Generated by Django 3.2.4 on 2021-06-23 20:45

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210623_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
